# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LiangCang_Proj' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiangCang_Proj
pod 'AFNetworking', '~> 3.1.0'
pod 'JSONModel', '~> 1.2.0'

end
